### ISSUE TITLE
cant start ETN wallet app on macOS Catalina

### ISSUE THREAD

**Issue by Mungg24** [andrepatta/etn-desktop-wallet#4]
when i start the ETN wallet app i get this error:

Process:               electroneum-wallet-gui [1232]
Path:                  /private/var/folders/*/ETN Desktop Wallet.app/Contents/MacOS/electroneum-wallet-gui
Identifier:            com.electroneum.electroneum-wallet-gui
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           electroneum-wallet-gui [1232]
User ID:               501

Date/Time:             2020-02-29 09:59:33.946 +0100
OS Version:            Mac OS X 10.15.3 (19D76)
Report Version:        12
Anonymous UUID:        C5CA5E9D-4864-6380-B2DB-0D19F23393A6

Time Awake Since Boot: 1200 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/unbound/lib/libunbound.8.dylib
  Referenced from: /private/var/folders/*/ETN Desktop Wallet.app/Contents/MacOS/electroneum-wallet-gui
  Reason: image not found

Binary Images:
       0x108444000 -        0x1092e2feb +com.electroneum.electroneum-wallet-gui (0) <DAC33AC5-3BD3-3CA8-884B-A743EC097B5F> /var/folders/*/ETN Desktop Wallet.app/Contents/MacOS/electroneum-wallet-gui
       0x109b0a000 -        0x109b9acb7  dyld (733.8) <EBC07CB6-870A-3A8E-B48A-67F62EA161F3> /usr/lib/dyld

**Comment by andrepatta** [comment]
Hi @Mungg24 ,

That's a known issue on OSX Catalina. As a workaround, please follow the steps 1 to 4 on the OS X section of the [Build & Run documentation](https://github.com/andrepatta/etn-desktop-wallet/blob/master/docs/build-and-run.md).

Thanks

**Comment by Mungg24** [comment]
Hi Andre

Unfortunately, it does still not work after following steps 1 to 4. Same error.
I even tried steps 1-8. But after building i see these messages and cannot start the app (because its broken):

clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
ld: warning: directory not found for option '-L/Users/Dani/electroneum-gui/electroneum/lib'
ld: library not found for -lwallet_merged
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [release/bin/electroneum-wallet-gui.app/Contents/MacOS/electroneum-wallet-gui] Error 1

**Comment by andrepatta** [comment]
Hi @Mungg24 ,

Sorry for the delay replying to your issue. Could you please pull latest changes from master branch and try again? Electroneum v3.2.0.0 was just release and it should fix the compilation issues you had.

Thanks

**Comment by Mungg24** [comment]
Hi @andrepatta 

Sorry, i did not have time for further testing till now.
I tried to create the app like described here step by step: https://github.com/andrepatta/etn-desktop-wallet/blob/master/docs/build-and-run.md

Bit i still get the same error at the end:

clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
ld: warning: directory not found for option '-L/Users/Dani/etn-desktop-wallet/electroneum/lib'
ld: library not found for -lwallet_merged
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [release/bin/electroneum-wallet-gui.app/Contents/MacOS/electroneum-wallet-gui] Error 1

I have downloaded the new Electroneum v3.2.0.0 release. But i dont understand why i need it to build the desktop wallet app?
